# Generated by Django 2.1.7 on 2019-02-20 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du contenu')),
                ('begin_date', models.DateTimeField(verbose_name="Début d'affichage")),
                ('end_date', models.DateTimeField(verbose_name="Fin d'affichage")),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(choices=[('I', 'Image uploadée'), ('U', 'URL'), ('Y', 'Youtube')], default='I', max_length=1)),
                ('content_url', models.CharField(max_length=255, null=True, verbose_name='Url du contenu')),
                ('state', models.CharField(choices=[('P', 'En attente'), ('A', 'Approuvé'), ('R', 'Rejeté')], default='P', max_length=1)),
                ('is_valid', models.BooleanField(default=False)),
                ('duration', models.IntegerField(verbose_name="Durée d'apparition à l'écran")),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du flux')),
            ],
        ),
        migrations.CreateModel(
            name='FeedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du groupe de flux')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contents')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'écran")),
                ('place', models.CharField(max_length=255, verbose_name="Lieu de l'écran")),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('date_last_call', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('load', models.CharField(blank=True, max_length=16, null=True)),
                ('fs_ro', models.BooleanField(default=False)),
                ('tv_screen_on', models.BooleanField(default=False)),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('owner_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('N', 'Normal'), ('U', 'Urgent')], default='N', max_length=1)),
                ('priority', models.IntegerField(verbose_name='Priorité')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Feed')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Screen')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.FeedGroup'),
        ),
        migrations.AddField(
            model_name='feed',
            name='moderator_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feed_moderator', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='feed',
            name='submitter_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feed_submitter', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='content',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_feed', to='app.Feed', verbose_name="Flux d'affichage"),
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
