# Generated by Django 2.1.7 on 2019-02-14 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du contenu')),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(choices=[('I', 'Image'), ('U', 'URL')], default='I', max_length=1)),
                ('content_url', models.CharField(max_length=255, null=True, verbose_name='Url du contenu')),
                ('content_file', models.ImageField(upload_to='contents')),
                ('state', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du flux')),
            ],
        ),
        migrations.CreateModel(
            name='FeedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du groupe de flux')),
                ('owner_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'écran")),
                ('place', models.CharField(max_length=255, verbose_name="Lieu de l'écran")),
                ('owner_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('N', 'Normal'), ('U', 'Urgent')], default='N', max_length=1)),
                ('priority', models.IntegerField(verbose_name='Priorité')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Feed')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Screen')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.FeedGroup'),
        ),
        migrations.AddField(
            model_name='feed',
            name='owner_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='auth.Group'),
        ),
    ]
