# Generated by Django 2.1.7 on 2019-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='feed',
            field=models.ManyToManyField(related_name='content_feed', to='app.Feed'),
        ),
    ]
