# Generated by Django 2.1.7 on 2019-02-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_content_feed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='owner_group',
            new_name='submitter_group',
        ),
    ]
