# Generated by Django 2.1.7 on 2019-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190218_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.IntegerField(default=10, verbose_name='Durée'),
            preserve_default=False,
        ),
    ]
