# Generated by Django 2.1.7 on 2019-02-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_file',
        ),
    ]
