# Generated by Django 2.1.7 on 2019-03-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_screen_date_last_monitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(
                    choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'),
                             (7, 'Dimanche')], default='1')),
                ('first_hour', models.TimeField()),
                ('last_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HourGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du groupe horaire')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du groupe horaire')),
                ('hour_group',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.HourGroup')),
            ],
        ),
        migrations.AddField(
            model_name='hour',
            name='hour_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour',
                                    to='app.HourGroup'),
        ),
        migrations.AddField(
            model_name='screen',
            name='place_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Place'),
        ),
    ]
