# Generated by Django 2.1.7 on 2019-03-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0006_auto_20190304_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
