# Generated by Django 2.1.7 on 2019-02-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_content_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('I', 'Image uploadée'), ('U', 'URL')], default='I', max_length=1),
        ),
    ]
