# Generated by Django 2.1.7 on 2019-03-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_auto_20190304_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
