# Generated by Django 2.1.7 on 2019-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190219_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedgroup',
            name='owner_group',
        ),
        migrations.AlterField(
            model_name='content',
            name='state',
            field=models.CharField(choices=[('P', 'En attente'), ('A', 'Approuvé'), ('R', 'Rejeté')], default='P', max_length=1),
        ),
    ]
