# Generated by Django 2.1.7 on 2019-02-19 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190219_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='height',
            field=models.IntegerField(default=1080),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='width',
            field=models.IntegerField(default=1920),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='begin_date',
            field=models.DateTimeField(verbose_name="Début d'affichage"),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('I', 'Image uploadée'), ('U', 'URL'), ('Y', 'Youtube')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.IntegerField(verbose_name="Durée d'apparition à l'écran"),
        ),
        migrations.AlterField(
            model_name='content',
            name='end_date',
            field=models.DateTimeField(verbose_name="Fin d'affichage"),
        ),
        migrations.AlterField(
            model_name='content',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_feed', to='app.Feed', verbose_name="Flux d'affichage"),
        ),
    ]
