# Generated by Django 2.1.7 on 2019-03-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0010_feed_date_last_moderation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_last_moderation_email',
            field=models.DateTimeField(null=True),
        ),
    ]
