# Generated by Django 2.1.7 on 2019-03-22 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20190320_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='reject_reason',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='user_moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
