# Generated by Django 2.1.7 on 2019-03-22 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0013_auto_20190322_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.SET_DEFAULT,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
