# Generated by Django 2.1.7 on 2019-03-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0014_auto_20190322_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='date_last_problem_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_control_type',
            field=models.IntegerField(
                choices=[(0, 'None'), (1, 'CEC RW'), (2, 'CEC RO'), (3, 'LG Serial'), (4, 'RPi TV Service')],
                default=0),
        ),
    ]
