# Generated by Django 2.1.7 on 2019-04-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0016_auto_20190327_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.IntegerField(default=7, verbose_name="Durée d'apparition à l'écran"),
        ),
    ]
